### ISSUE TITLE
dgplug newsletter issues #5 - planned release May 2018

### ISSUE THREAD

**Issue by ghost** [dgplug/newsletter#11]
Further contents for issue `#5` of the newsletter

**Comment by farhaanbukhsh** [comment]
https://www.youtube.com/watch?v=wlR5gYd6um0

Mastering the vim language is one of those videos which gave me deeper insight in how to use vim more efficiently.

**Comment by SaptakS** [comment]
https://www.youtube.com/watch?v=3WS9DhSIWR0 - The Declaration of Independence of Cyberspace as written by John Perry Barlow, read by John Perry Barlow.

**Comment by kushaldas** [comment]
https://www.eff.org/pages/tor-and-https

**Comment by ghost** [comment]
https://www.eff.org/deeplinks/2018/04/dc-court-accessing-public-information-not-computer-crime

**Comment by sayanchowdhury** [comment]
How python's import machinery works https://manikos.github.io/how-pythons-import-machinery-works

**Comment by jasonbraganza** [comment]
Seth Godin’s new project is a podcast called Akimbo.
It’s a show about … well, darn near everything about people and life and relationships
Consider this your real life MBA.

Ones I specially loved were episode 2 on status and episode 8 on quality and the love of human imperfections (wabi-sabi)

https://www.akimbo.me

**Comment by jasonbraganza** [comment]
This Is How To Sleep Better: 5 Secrets From Neuroscience

https://www.bakadesuyo.com/2018/04/how-to-sleep-better/

**Comment by jasonbraganza** [comment]
To everyone who asks for ‘just a little’ of your time: here’s what it costs to say yes

https://ryanholiday.net/to-everyone-who-asks-for-just-a-little-of-your-time-heres-what-it-costs-to-say-yes/

**Comment by jasonbraganza** [comment]
Apparently NASA does not want to heed the alien’s warning 

ALL THESE WORLDS ARE YOURS—EXCEPT EUROPA
ATTEMPT NO LANDING THERE.

https://arstechnica.com/science/2018/04/if-were-really-going-to-europa-nasa-needs-to-pick-a-rocket-soon/

**Comment by jasonbraganza** [comment]
I rarely steamroll people, but @Schubisu, this post just **has** to go into the next issue :)

First Principles: The Building Blocks of True Knowledge
https://www.fs.blog/2018/04/first-principles/

**Comment by jasonbraganza** [comment]
How to Commit to Long-Term Goals

https://www.scotthyoung.com/blog/2018/04/17/commit-long-term-goals/

**Comment by ghost** [comment]
https://www.theverge.com/2018/4/18/17253784/google-domain-fronting-discontinued-signal-tor-vpn

**Comment by jasonbraganza** [comment]
Barbara Oakley & Shane Parrish on Learning How to Learn

https://www.fs.blog/2018/04/learning-barbara-oakley/

**Comment by ghost** [comment]
Thanks for all your comments!
Please add further suggestions to issue #12 to be taken into account for letter `#6`.
