### ISSUE TITLE
dgplug newsletter issues #6 - planned release May/June 2018

### ISSUE THREAD

**Issue by ghost** [dgplug/newsletter#12]
Further contents for issue `#6` of the newsletter

**Comment by jasonbraganza** [comment]
Go Fast and Break Things: The Difference Between Reversible and Irreversible Decisions

https://www.fs.blog/2018/04/reversible-irreversible-decisions/

**Comment by gauravsitlani** [comment]
I wrote a blog post about delivering talks in Golang and Python Pune meetup April 2018.
https://gauravsitlani.wordpress.com/

**Comment by jasonbraganza** [comment]
Inertia: The Force That Holds the Universe Together

https://www.fs.blog/2018/04/inertia/

**Comment by jasonbraganza** [comment]
Freelancers. The latest episode in the Akimbo podcast.

If you ever entertained the slightest thought about working for yourself, do your self a favour and listen to this episode of Seth’s podcast
https://art19.com/shows/akimbo/episodes/d2dfae11-26cd-4c67-86d1-b1c0c24bf3bb

**Comment by jasonbraganza** [comment]
+ Earning Your Stripes — On this episode of The Knowledge Project Podcast (full transcript included), Patrick Collison, CEO, and co-founder of Stripe shares wise insights on success, failure, management, decision making, learning and so much more. Grab a pen... 

Audio - http://traffic.libsyn.com/theknowledgeproject/TKP_Patrick_Collison.mp3
Text - https://s3.amazonaws.com/fs-lc/2018/Podcast/Transcripts/Patrick+Collison.pdf

**Comment by jasonbraganza** [comment]
Weekend Guitar noodling by Steve Krenz
When I was starting out on guitar, I wish someone would have handed me a few pages and said "Hey kid, here are the chord forms you will use for the rest of your life as a professional guitarist."

Chords - https://gx169.infusionsoft.com/app/linkClick/11009/9ee65e6f7e430543/2759575/6ca86e4a144e2dd8

Lesson - https://gx169.infusionsoft.com/app/linkClick/11023/9f0cbfa579fa3c72/2759575/6ca86e4a144e2dd8

**Comment by jasonbraganza** [comment]
13 Life-Changing Habits To Try And Do Every Single Day

https://ryanholiday.net/13-life-changing-habits-to-try-and-do-every-single-day/

**Comment by jasonbraganza** [comment]
General Thinking Tools: 9 Mental Models to Solve Difficult Problems

https://www.fs.blog/general-thinking-tools/

**Comment by jasonbraganza** [comment]
aah, this issue is still open, so I’ll just tack the link here :)

Smarter, Not Harder: How to Succeed at Work
https://www.fs.blog/2018/06/succeed-at-work/

**Comment by kushaldas** [comment]
https://www.youtube.com/watch?v=B0xqrNMR1q4 Talk form nullcon 2018 on "Privacy and Surveillance"

**Comment by kushaldas** [comment]
>Weekend Guitar noodling by Steve Krenz

Maybe we can skip Guitar lessons in the newsletter. We should add a blog post link from you on the same though :)

**Comment by jasonbraganza** [comment]
On Mon, 25 Jun 2018 at 16:03, Kushal Das <notifications@github.com> wrote:

> Maybe we can skip Guitar lessons in the newsletter. We should add a blog
> post link from you on the same though :)
>

I just post links :)
I leave the editorial entirely in more capable hands :)

Warmest,
Jason

>

**Comment by kushaldas** [comment]
https://saveourprivacy.in/

**Comment by kushaldas** [comment]
https://www.bbc.com/news/technology-44628869

**Comment by kushaldas** [comment]
https://thewire.in/tech/secrecy-abounds-the-creation-of-of-indias-internet-shutdown-law-why

**Comment by kushaldas** [comment]
http://locusmag.com/2018/07/cory-doctorow-zucks-empire-of-oily-rags/

**Comment by ghost** [comment]
The happy collection continues in the next issue #13
