### ISSUE TITLE
dgplug newsletter issue #1 - release 25 FEB 2018

### ISSUE THREAD

**Issue by ghost** [dgplug/newsletter#3]
To publish a first issue, it will probably take some days to get some infrastructure in place and handle some general questions, so the release date is yet unknown / to be discussed.
I will add a summary of the IRC meeting that will be part of the first issue.

**Feel free to post further ideas / topics you would like to see in the upcoming newsletter!**

**Comment by kushaldas** [comment]
https://opensource.com/article/18/2/coining-term-open-source-software

**Comment by kushaldas** [comment]
https://sausheong.github.io/posts/space-invaders-with-go/

**Comment by ghost** [comment]
https://www.eff.org/press/releases/catalog-missing-devices-illustrates-gadgets-could-and-should-exist

**Comment by kushaldas** [comment]
https://lcamtuf.blogspot.com/2018/02/on-leadership.html

**Comment by ghost** [comment]
https://github.com/dgplug/infrastructure/issues/9
