### ISSUE TITLE
dgplug newsletter issues #2 - release 11 MAR 2018

### ISSUE THREAD

**Issue by ghost** [dgplug/newsletter#5]
https://jacobian.org/writing/python-environment-2018/

**Comment by kushaldas** [comment]
https://geeksocket.in/blog/contributing-diceware-tool/ this is from @bhavin192

**Comment by bhavin192** [comment]
I found this post interesting, https://blog.cloudflare.com/using-go-as-a-scripting-language-in-linux/

**Comment by jasonbraganza** [comment]
This was my introduction to Susan Fowler. She was my hero (because obviously, she’s a super autodidact) long before her blockbuster sex discrimination awareness post on Uber

https://www.susanjfowler.com/blog/2016/8/13/so-you-want-to-learn-physics

**Comment by kushaldas** [comment]
https://www.wired.com/story/chrome-yubikey-phishing-webusb/

**Comment by kushaldas** [comment]
https://githubengineering.com/ddos-incident-report/

**Comment by jasonbraganza** [comment]
Which dragon are you battling now? How and where is your ego holding you back from making progress? Have you been preparing too long to act? Have you been waiting for others to finish the battle for you? Have you been using others to avoid the next step you know you must take?

Are you ready to slay the dragon yourself?

Here’s 21 days to self reliance!

https://www.artofmanliness.com/2018/02/28/31-days-greater-self-reliance/

**Comment by kushaldas** [comment]
https://rfc.dgplug.org/
We have this for long time, not many knows about this one. We should add a description of what is RFC and why should people read them :)

**Comment by jasonbraganza** [comment]
How to Read More Books This Year, via The Art of Manliness

https://www.artofmanliness.com/2018/02/26/how-to-read-more-books/

**Comment by jasonbraganza** [comment]
You need a reset day

https://www.artofmanliness.com/2018/03/05/need-reset-day/

**Comment by kushaldas** [comment]
A must read for everyone https://dev.to/ashleymcnamara/nevertheless-ashley-mcnamara-coded--23ag

**Comment by kushaldas** [comment]
There is a stable release of Tor https://blog.torproject.org/new-stable-tor-releases-security-fixes-and-dos-prevention-03210-03110-02915

**Comment by kushaldas** [comment]
I guess this is being delayed by 1 week.

**Comment by kushaldas** [comment]
https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

**Comment by ghost** [comment]
Sorry, as @kushaldas said I this has been delayed by one week. I close this issue as the content collection for the March release is completed, please put all further links etc to the next issue (#6 )

I've pushed a first draft for the current release, anyone who already read some of the provided links and articles, please feel free to add some descriptive lines.
