### ISSUE TITLE
dgplug newsletter issues #3 - release 02 APR 2018 

### ISSUE THREAD

**Issue by ghost** [dgplug/newsletter#6]
Further readings for issue `#3` of the newsletter

**Comment by jasonbraganza** [comment]
Digital currencies are generating a lot of excitement. 
John Oliver enlists Keegan-Michael Key to get potential investors equally excited about the concept of caution.

https://www.youtube.com/watch?v=g6iDZspbRMg

**Comment by jasonbraganza** [comment]
Masters at work across several domains. (via Ramit Sethi’s newsletter)

Would love to be a programmer this good!

http://links.iwillteachyoutoberich.com/a/258/preview/6236692/742102865/6aa2f5ca9c2175ff2018a85e6a05113db98d6dcb?message_id=Ijc0NTZmZGMwLTA5YzMtMDEzNi04MzIwLTE0MDJlYzZmMWMyY0Bpd2lsbHRlYWNoeW91dG9iZXJpY2guY29tIg==

**Comment by kushaldas** [comment]
https://mtlynch.io/why-i-quit-google/

**Comment by kushaldas** [comment]
>Digital currencies are generating a lot of excitement.
John Oliver enlists Keegan-Michael Key to get potential investors equally excited about the concept of caution.|

I would prefer all digital currency related things outside as they create a lot of bikeshed momenets

**Comment by jasonbraganza** [comment]
Steve Jobs’ prescience on developing products at scale and on the importance of “doing”, of developing scar tissue …

https://www.youtube.com/watch?v=Gk-9Fd2mEnI

**Comment by kushaldas** [comment]
http://www.repubblica.it/esteri/2018/03/19/news/snowden_how_the_deep_state_shapes_presidents_-191619170/?refresh_ce

**Comment by jasonbraganza** [comment]
The Art of Thinking Clearly

https://www.fs.blog/2013/09/the-art-of-thinking-clearly/

**Comment by jasonbraganza** [comment]
Cal Newport on “slow social media” and how to effectively gain a social presence on the web.
(Hint: get a blog)

http://calnewport.com/blog/2018/03/25/beyond-deletefacebook-more-thoughts-on-embracing-the-social-internet-over-social-media/

**Comment by ghost** [comment]
I'm closing this for wrap up in the next issue. Please use #9 for posting further contents.
