### ISSUE TITLE
dgplug newsletter issues #4 - planned release 16 APR 2018 

### ISSUE THREAD

**Issue by ghost** [dgplug/newsletter#9]
Further contents for issue `#4` of the newsletter

**Comment by kushaldas** [comment]
https://www.jetbrains.com/research/python-developers-survey-2017/

**Comment by kushaldas** [comment]
https://motherboard.vice.com/en_us/article/zmg3ky/surveillance-memes-nsa-fbi-facebook

**Comment by bhavin192** [comment]
https://blog.cloudflare.com/dns-resolver-1-1-1-1

**Comment by SaptakS** [comment]
For UI/UX and Frontend designers: https://lawsofux.com/fittss-law.html

**Comment by SaptakS** [comment]
Another web design: https://www.nngroup.com/articles/top-10-mistakes-web-design/

**Comment by jasonbraganza** [comment]
On the end of Windows
https://stratechery.com/2018/the-end-of-windows/

**Comment by jasonbraganza** [comment]
Words on Slides
http://sethgodin.typepad.com/seths_blog/2018/04/words-on-slides.html

**Comment by jasonbraganza** [comment]
Notes on the current state of encrypted DNS (makes a good follow up to @bhavin192’s Cloudfare article)

https://arstechnica.com/information-technology/2018/04/how-to-keep-your-isps-nose-out-of-your-browser-history-with-encrypted-dns/

**Comment by ghost** [comment]
I close this round of resource collection in favour of #11 for the next upcoming release
